"""
.pptx renderer for the Presentation Outliner agent.

Takes a DeckSpec (the JSON shape the Outliner prompt emits, validated as a
Pydantic model in spec.py) and produces a branded .pptx using python-pptx.

V1 scope:
  - Three layouts: title, title_content (bulleted body), section.
  - C-HAWQ brand styling (colors from writing-rules.md).
  - Speaker notes on every slide that supplies them.
  - Safe handling for missing / oversized fields (the agent will sometimes
    return more bullets than fit; we cap rather than error).

What V1 does NOT do:
  - Custom layouts beyond the three above (charts, images, two-column).
  - True branded master template (.potx). V1 builds slides from python-pptx
    defaults and applies brand styling per shape. Swap in a real .potx in V2
    by changing _new_presentation() — the rest of the renderer keeps working.
  - Font fallback handling. python-pptx writes the font NAME into the XML;
    actual rendering depends on the viewing system having the font. C-HAWQ's
    Futura PT and Source Sans 3 may not be on every reviewer's machine; on
    those machines PowerPoint substitutes, which is fine for V1.
"""
from __future__ import annotations

import io
import logging
from pathlib import Path
from typing import Iterable

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

from .spec import DeckSpec, Slide

logger = logging.getLogger(__name__)


# --- Brand tokens (writing-rules.md) ----------------------------------------

BRAND_BLUE = RGBColor(0x1F, 0x39, 0x6D)       # main blue
BRAND_GREEN = RGBColor(0x3F, 0x88, 0x6C)      # secondary green
BRAND_BLUE_LIGHT = RGBColor(0x48, 0xC5, 0xE3) # secondary blue
BRAND_INK = RGBColor(0x1A, 0x1A, 0x1A)        # near-black for body
BRAND_PAPER = RGBColor(0xFF, 0xFF, 0xFF)      # white background

HEADING_FONT = "Futura PT"
BODY_FONT = "Source Sans 3"
DATA_FONT = "Source Code Pro"

# 16:9 layout. python-pptx defaults to 4:3 unless overridden.
SLIDE_WIDTH = Inches(13.333)
SLIDE_HEIGHT = Inches(7.5)

# Body bullet cap — beyond this, the agent gave us too many; we drop the
# overflow and log a warning rather than producing a slide that overflows.
MAX_BULLETS = 6


# --- Public API -------------------------------------------------------------

def render_deck(spec: DeckSpec) -> bytes:
    """
    Render a DeckSpec into .pptx bytes. Caller decides whether to save to
    disk, mirror to Drive, or stream to a response.
    """
    prs = _new_presentation(spec)

    for index, slide_spec in enumerate(spec.slides):
        try:
            _render_slide(prs, slide_spec)
        except Exception as exc:
            # One bad slide shouldn't kill the whole render. Log and
            # render a placeholder so reviewers see exactly which slide
            # had a problem — easier to debug than a missing slide.
            logger.exception(
                "pptx render error — emitting placeholder slide",
                extra={"slide_index": index, "title": slide_spec.title},
            )
            _render_error_slide(prs, slide_spec, exc)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


def render_deck_to_file(spec: DeckSpec, path: str | Path) -> Path:
    """Convenience: render and write to disk. Returns the absolute path."""
    out = Path(path).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(render_deck(spec))
    return out


# --- Internals --------------------------------------------------------------

def _new_presentation(spec: DeckSpec) -> Presentation:
    """Build a fresh 16:9 presentation and stamp core properties."""
    prs = Presentation()
    prs.slide_width = SLIDE_WIDTH
    prs.slide_height = SLIDE_HEIGHT

    cp = prs.core_properties
    cp.title = spec.title
    if spec.author:
        cp.author = spec.author
    cp.comments = "Generated by C-HAWQ Presentation Outliner agent."
    return prs


def _render_slide(prs: Presentation, s: Slide) -> None:
    """Dispatch to the matching layout renderer."""
    if s.layout == "title":
        _render_title_slide(prs, s)
    elif s.layout == "section":
        _render_section_slide(prs, s)
    else:
        _render_title_content_slide(prs, s)


def _render_title_slide(prs: Presentation, s: Slide) -> None:
    """Cover slide. Brand-blue background, big white title, optional subtitle."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    _set_solid_fill(slide.background, BRAND_BLUE)

    title_box = slide.shapes.add_textbox(
        Inches(0.75), Inches(2.5), Inches(11.83), Inches(2.0)
    )
    _write_text(
        title_box.text_frame,
        s.title,
        font=HEADING_FONT,
        size=Pt(54),
        bold=True,
        color=BRAND_PAPER,
    )

    if s.subtitle:
        sub_box = slide.shapes.add_textbox(
            Inches(0.75), Inches(4.6), Inches(11.83), Inches(1.0)
        )
        _write_text(
            sub_box.text_frame,
            s.subtitle,
            font=BODY_FONT,
            size=Pt(24),
            bold=False,
            color=BRAND_BLUE_LIGHT,
        )

    _attach_speaker_notes(slide, s.speaker_notes)


def _render_section_slide(prs: Presentation, s: Slide) -> None:
    """Section divider. Brand-green band on the left, dark title on white."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _set_solid_fill(slide.background, BRAND_PAPER)

    # Vertical accent band.
    band = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE, Inches(0), Inches(0), Inches(0.4), SLIDE_HEIGHT
    )
    band.line.fill.background()
    _set_solid_fill(band.fill, BRAND_GREEN)

    title_box = slide.shapes.add_textbox(
        Inches(0.9), Inches(3.0), Inches(11.6), Inches(1.5)
    )
    _write_text(
        title_box.text_frame,
        s.title,
        font=HEADING_FONT,
        size=Pt(40),
        bold=True,
        color=BRAND_BLUE,
    )

    if s.subtitle:
        sub_box = slide.shapes.add_textbox(
            Inches(0.9), Inches(4.4), Inches(11.6), Inches(0.8)
        )
        _write_text(
            sub_box.text_frame,
            s.subtitle,
            font=BODY_FONT,
            size=Pt(18),
            color=BRAND_INK,
        )

    _attach_speaker_notes(slide, s.speaker_notes)


def _render_title_content_slide(prs: Presentation, s: Slide) -> None:
    """Default body slide. Title at top, bulleted body below."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank
    _set_solid_fill(slide.background, BRAND_PAPER)

    # Title.
    title_box = slide.shapes.add_textbox(
        Inches(0.6), Inches(0.4), Inches(12.1), Inches(0.9)
    )
    _write_text(
        title_box.text_frame,
        s.title,
        font=HEADING_FONT,
        size=Pt(32),
        bold=True,
        color=BRAND_BLUE,
    )

    # Underline accent.
    accent = slide.shapes.add_shape(
        MSO_SHAPE.RECTANGLE, Inches(0.6), Inches(1.3), Inches(1.2), Emu(35000)
    )
    accent.line.fill.background()
    _set_solid_fill(accent.fill, BRAND_GREEN)

    # Body bullets.
    bullets = list(s.bullets)
    if len(bullets) > MAX_BULLETS:
        logger.warning(
            "pptx render — bullet overflow, dropping tail",
            extra={
                "slide_title": s.title,
                "bullet_count": len(bullets),
                "max": MAX_BULLETS,
            },
        )
        bullets = bullets[:MAX_BULLETS]

    body_box = slide.shapes.add_textbox(
        Inches(0.6), Inches(1.7), Inches(12.1), Inches(5.4)
    )
    tf = body_box.text_frame
    tf.word_wrap = True

    for idx, bullet in enumerate(bullets):
        para = tf.paragraphs[0] if idx == 0 else tf.add_paragraph()
        para.text = bullet
        para.alignment = PP_ALIGN.LEFT
        for run in para.runs:
            run.font.name = BODY_FONT
            run.font.size = Pt(20)
            run.font.color.rgb = BRAND_INK

    _attach_speaker_notes(slide, s.speaker_notes)


def _render_error_slide(prs: Presentation, s: Slide, exc: Exception) -> None:
    """Visible placeholder when a slide fails to render — better than silence."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_solid_fill(slide.background, BRAND_PAPER)

    title_box = slide.shapes.add_textbox(
        Inches(0.6), Inches(0.5), Inches(12.1), Inches(1.0)
    )
    _write_text(
        title_box.text_frame,
        f"[Render error] {s.title}",
        font=HEADING_FONT,
        size=Pt(28),
        bold=True,
        color=BRAND_BLUE,
    )

    detail_box = slide.shapes.add_textbox(
        Inches(0.6), Inches(1.7), Inches(12.1), Inches(5.0)
    )
    _write_text(
        detail_box.text_frame,
        f"This slide failed to render. {type(exc).__name__}: {exc}",
        font=BODY_FONT,
        size=Pt(16),
        color=BRAND_INK,
    )


# --- Tiny helpers -----------------------------------------------------------

def _set_solid_fill(fill_or_background, rgb: RGBColor) -> None:
    """
    python-pptx fill objects (shape.fill) and slide backgrounds expose the
    same .fill API but reach it through different attribute paths. Wrap so
    callers don't have to remember which is which.
    """
    target = getattr(fill_or_background, "fill", fill_or_background)
    target.solid()
    target.fore_color.rgb = rgb


def _write_text(
    tf,
    text: str,
    *,
    font: str,
    size: Pt,
    bold: bool = False,
    color: RGBColor | None = None,
) -> None:
    """Single-paragraph text, fully styled. Replaces whatever's in the frame."""
    tf.clear()
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.name = font
    run.font.size = size
    run.font.bold = bold
    if color is not None:
        run.font.color.rgb = color


def _attach_speaker_notes(slide, notes: str | None) -> None:
    if not notes:
        return
    notes_tf = slide.notes_slide.notes_text_frame
    notes_tf.text = notes
    for para in notes_tf.paragraphs:
        for run in para.runs:
            run.font.name = BODY_FONT
            run.font.size = Pt(11)


def iter_slide_titles(spec: DeckSpec) -> Iterable[str]:
    """Convenience for tests / logs — list every slide title in order."""
    return (s.title for s in spec.slides)
