steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'jobs/email_scraper'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/chawq-manatee-matinee/internal-tools/inbox-scraper:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'jobs/email_scraper'
    args: ['push', 'us-central1-docker.pkg.dev/chawq-manatee-matinee/internal-tools/inbox-scraper:latest']
images:
  - 'us-central1-docker.pkg.dev/chawq-manatee-matinee/internal-tools/inbox-scraper:latest'

serviceAccount: 'projects/chawq-manatee-matinee/serviceAccounts/chawq-builder@chawq-manatee-matinee.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY